name: brakecode-alert
on:
  workflow_dispatch

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:

    - name: Call BrakeCODE API via GitHub Action
      uses: june07/brakecode-alert-github-action@v1-beta5
      with:
        api-key: ${{ secrets.BRAKECODE_API_KEY }}
        title: "test title"
        content: "test content"
        badge-text: "test badge text"
        badge-color: "#FF9800"
